### ISSUE TITLE
'terminal-table/import' cannot be required as before

### ISSUE THREAD

**Issue by cdlm** [tj/terminal-table#58]
Apparently this was the way to load previous versions of terminal-table. But since the current file tries to include a module without doing any require before, it now fails. This breaks [flavio/jump](https://github.com/flavio/jump), for instance (even though it depends on `~> 1.4`…)

**Comment by nateberkopec** [comment]
Thanks for the report - I'm brand new to this project as maintainer, and people were pushing hard for a release, so there's going to be some teething problems here as we get things back under control!

In a future release, I think I'll make it so that you should just require terminal-table as you normally would, and then include the TableHelper module yourself and do away with "import" altogether. But that's not fair to do immediately, so I'll fix this.

**Comment by nateberkopec** [comment]
EDIT: As a workaround until I release a fix for this as 1.5.2, you can of course just require 'terminal-table' before requiring 'terminal-table/import'.

**Comment by cdlm** [comment]
Yup, I tried that, it seemed to help, but I ran in other problems afterwards. `jump` should really not be loading 1.5 at the moment.

**Comment by nateberkopec** [comment]
Fix pushed in 1.5.2

**Comment by nateberkopec** [comment]
@cdlm Any help you can provide identifying issues with 1.5.x would be greatly appreciated!

**Comment by cdlm** [comment]
Unfortunately, I won't have a lot of brain time available in the next weeks… but I use `jump` a lot so I'll probably try to scratch my itches with it sometime during the summer.
